services:
  discord-bot:
    build: .
    image: localhost:5000/bozobot-discord-bot:latest
    container_name: discord-bot
    command: ["python", "discord_bot.py"]
    env_file:
      - .env
    volumes:
      - ${HOST_MEDIA_PATH}:${MEDIA_PATH}
    networks:
      - internal
    restart: always

  fastapi-server:
    build: .
    image: localhost:5000/bozobot-fastapi-server:latest
    container_name: fastapi-server
    command: ["python", "fastapi_server.py"]
    ports:
      - "${PORT_FASTAPI}:${PORT_FASTAPI}"
    env_file:
      - .env
    volumes:
      - ${HOST_MEDIA_PATH}:${MEDIA_PATH}
    networks:
      - internal
    depends_on:
      - discord-bot
    restart: always

networks:
  internal:
    driver: bridge
